name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      #- run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
#      - run: docker run -e CI=true cygnetops/react-test npm test
      - run: docker build -t cygnetops/react-app .
      - run: docker run -p 8080:80 -e CI=true cygnetops/react-app
  
  stop:
    runs-on: self-hosted
    steps:
    - name: manual approve
      run: |
        echo "Manually approved"
    - uses: actions/checkout@v3
    - run: docker stop cygnetops/react-app
